abstract class States {}
class AppInitialState extends States{}
class LoadDataFromAPIState extends States{}
class GetDataFromAPISuccessState extends States{}
class GetDataFromAPIFailedState extends States{}
class PutDataAPIFailedState extends States{}
class PutDataAPISuccessState extends States{}
class PostDataAPIFailedState extends States{}
class PostDataAPISuccessState extends States{}
